title:        "Arthur Zey"
description:  "Mortal Enemy of Chaos and Entropy <br />(or \"The Truth about the Dishwasher\")"
timezone:     UTC
theme:        jekyll-theme-cayman
url:          "http://www.arthurzey.com"
google_analytics: UA-163771135-1
plugins:
  - jekyll-sitemap
include:      ['_pages']
exclude:
  - Gemfile
  - Gemfile.lock
relative_permalinks: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Arthur Zey"
  -
    scope:
      path: "assets/images"
    values:
      image: true
      sitemap: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:year-:month-:day/:slug/
      layout: "post"
  -
    scope:
      path: "_posts/diary"
      type: "posts"
    values:
      permalink: /diary/:year-:month-:day/
      layout: "post"
  -
    scope:
      path: "_pages"
    values:
      layout: "page"
      permalink: /:basename/
