title:        "Arthur Zey"
description:  "The blog (and maybe whole website?) for Arthur Zey"
timezone:     UTC
theme:        jekyll-theme-cayman
include:      ['_pages']
relative_permalinks: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Arthur Zey"
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:year-:month-:day/:slug
  -
    scope:
      path: "_posts/diary"
      type: "posts"
    values:
      permalink: /blog/diary/:year-:month-:day/
  -
    scope:
      path: "_pages"
    values:
      layout: "page"
