title:        "Arthur Zey"
description:  "The blog (and maybe whole website?) for Arthur Zey"
timezone:     UTC
theme:        jekyll-theme-cayman
include:      ["_docs/"]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Arthur Zey"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:slug
  -
    scope:
      path: ""
      type: "posts"
      category: "diary"
    values:
      permalink: /blog/:categories/:year-:month-:day/
  -
    scope:
      path: "_docs"
    values:
      layout: "doc"
      permalink: /:slug
