title:        "Arthur Zey"
description:  "Mortal Enemy of Chaos and Entropy <br />(or \"The Truth about the Dishwasher\")"
timezone:     UTC
theme:        jekyll-theme-cayman
include:      ['_pages']
exclude:
  - Gemfile
  - Gemfile.lock
relative_permalinks: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Arthur Zey"
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:year-:month-:day/:slug
  -
    scope:
      path: "_posts/diary"
      type: "posts"
    values:
      permalink: /diary/:year-:month-:day/
  -
    scope:
      path: "_pages"
    values:
      layout: "page"
      permalink: /:basename/
